#! /bin/bash
# test.sh: runs all test files, builds project, and runs executable

# test
go test ./main/...
go test ./lexer/...
go test ./parser/...
go test ./eval/...
# build
go build -o go-mix ./main
# run
go run ./main/
