#! /bin/bash
# test.sh: runs all test files and runs the main file
go test ./main/...
go test ./lexer/...
go test ./parser/...
go test ./eval/...

# build
go build -o go-mix ./main
# run
go run ./main/
